name = "TupleVectors"
uuid = "615932cf-77b6-4358-adcd-5b7eba981d7e"
authors = ["Chad Scherrer <chad.scherrer@gmail.com> and contributors"]
version = "0.1.5"

[deps]
ArraysOfArrays = "65a8f2f4-9b39-5baf-92e2-a9cc46fdf018"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
GeneralizedGenerated = "6b9d7cbe-bcb9-11e9-073f-15a7a543e2eb"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
NestedTuples = "a734d2a7-8d68-409b-9419-626914d4061d"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[compat]
ArraysOfArrays = "0.5"
ElasticArrays = "1"
GeneralizedGenerated = "0.3"
MacroTools = "0.5"
NestedTuples = "0.3"
Requires = "1.1"
StatsBase = "0.33"
StructArrays = "0.5, 0.6"
julia = "1"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MeasureTheory = "eadaa1a4-d27c-401d-8699-e962e1bbc33b"
Sobol = "ed01d8cd-4d21-5b2a-85b4-cc3bdc58bad4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "LinearAlgebra", "MeasureTheory", "Sobol"]
